apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ibgateway-live.fullname" . }}
  labels:
    {{- include "ibgateway-live.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "ibgateway-live.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "ibgateway-live.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      restartPolicy: Always
      serviceAccountName: {{ include "ibgateway-live.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: TWSUSERID
              valueFrom:
                secretKeyRef:
                  key: twsUserID
                  name: {{ .Release.Name }}-auth
            - name: TWSPASSWORD
              valueFrom:
                secretKeyRef:
                  key: twsPassword
                  name: {{ .Release.Name }}-auth
            - name: TRADING_MODE
              value: "live"
            - name: TWSMAJORVRSN
              value: "1012"
            - name: XVFB_ARGS
              value: '"-ac -screen 0 1024x768x16 +extension RANDR"'
            - name: FIXUSERID
            - name: FIXPASSWORD
          ports:
            - containerPort: 5900
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
